backend:
  name: git-gateway
  repo: pmcp/podiumaanhuis

# when using the default proxy server port
# To run local backend git: npx netlify-cms-proxy-server
local_backend: true

media_folder: "src/assets/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow


collections:
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "entries"
    label: "Voorstellingen"
    folder: "entries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Omschrijving", name: "descr", widget: "string"}
      - {label: "Leeftijd", name: "age", widget: "string"}
      - {label: "Video Link", name: "videoUrl", widget: "string"}
      - {label: "Video Lengte", name: "videoLength", widget: "string"}
      - {label: "Social tekstje", name: "socialDescr", widget: "string"}
      - {label: "Social Afbeelding", name: "socialImage", widget: "image"}
      - {label: "Info", name: "info", widget: "markdown"}
      - {label: "Opgenomen", name: "recordedAt", widget: "string"}
      - {label: "Company", name: "company", widget: "string"}
      - {label: "Afbeelding", name: "image", widget: "image"}
      - {label: "text", name: "text", widget: "markdown"}
      # TODO:
        # related fields: genre & company 
        # list field for info
  - name: "homepages"
    label: "Homepage"
    files:
      - label: "Home"
        name: "home"
        file: "pages/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Hoofdafbeelding, name: heroImage, widget: image}
          - {label: Hoofdafbeelding - Credit, name: heroCredit, widget: markdown}