backend:
  name: git-gateway
  repo: pmcp/podiumaanhuis
  branch: master

# when using the default proxy server port
# To run local backend git: npx netlify-cms-proxy-server
local_backend: false

media_folder: "src/assets/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow


collections:
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "entries"
    label: "Voorstellingen"
    folder: "entries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string", required: false}
      - {label: "Omschrijving", name: "descr", widget: "markdown", required: false}
      - {label: "Leeftijd", name: "age", widget: "string", required: false}
      - {label: "Video Link", name: "videoUrl", widget: "string", required: false}
      - {label: "Video Lengte", name: "videoLength", widget: "string", required: false}
      - {label: "Social tekstje", name: "socialDescr", widget: "string", required: false}
      - {label: "Social Afbeelding", name: "socialImage", widget: "image", required: false}
      - {label: "Opgenomen", name: "recordedAt", widget: "string", required: false}
      - {label: "Company", name: "company", widget: "string", required: false}
      - {label: "Afbeelding", name: "image", widget: "image", required: false}
      - {label: "text", name: "text", widget: "markdown", required: false}
      - {label: "Genre", name: "genre", widget: "relation", collection: "genres", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      - {label: "Publiek", name: "audience", widget: "relation", collection: "audiences", searchFields: ["title"], valueField: "title", displayFields: ["title"]}
      # TODO:
        # related fields: genre & company 
        # list field for info
  - name: "homepages"
    label: "Homepage"
    files:
      - label: "Home"
        name: "home"
        file: "pages/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Hoofdafbeelding, name: heroImage, widget: image}
          - {label: Hoofdafbeelding - Credit, name: heroCredit, widget: markdown}
          - {label: Formulier - Titel, name: formTitle, widget: string}
          - {label: Formulier - Tekst, name: formText, widget: markdown}
  - name: "genres"
    label: "Genres"
    folder: "genres"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}
  - name: "audiences"
    label: "Publiek"
    folder: "audiences"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}