backend:
  name: git-gateway
  repo: pmcp/podiumaanhuis

# when using the default proxy server port
# To run local backend git: npx netlify-cms-proxy-server
local_backend: true

media_folder: "static/uploads"
public_folder: "uploads"
# media_library:
#   name: uploadcare
#   config:
    # publicKey: 338fd3c82780b606487f
# publish_mode: editorial_workflow


collections:
  - name: "pages"
    label: "paginas"
    editor:
      preview: false
    label_singular: "pagina"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "entries"
    label: "voorstellingen"
    folder: "entries"
    editor:
      preview: false
    label_singular: "voorstelling"
    preview_path: voorstellingen/{{title}}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titel", name: "title", widget: "string", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - label: 'Publish Date'
        name: 'publishDate'
        widget: 'datetime'
      - {label: "text", name: "text", widget: "markdown", required: false}      
      - {label: "Afbeelding", name: "image", widget: "image", required: false} 
      - {label: "Opgenomen", name: "recordedAt", widget: "string", required: false}
      - {label: "Company", name: "company", widget: "string", required: false}
      - {label: "Omschrijving", name: "descr", widget: "markdown", required: false}
      - {label: "Genre", name: "genre", widget: "relation", collection: "genres", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false}
      - {label: "Publiek", name: "audience", widget: "relation", collection: "audiences", searchFields: ["title"], valueField: "title", displayFields: ["title"], required: false}
      - {label: "Leeftijd", name: "age", widget: "string", required: false}
      - {label: "Video Link", name: "videoUrl", widget: "string", required: false}
      - {label: "Video Lengte", name: "videoLength", widget: "string", required: false}
      - {label: "Social tekstje", name: "socialDescr", widget: "string", required: false}
      - {label: "Social Afbeelding", name: "socialImage", widget: "image", required: false}
  - name: "homepages"
    label: "Homepage"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "pages/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Hoofdafbeelding, name: heroImage, widget: image}
          - {label: Hoofdafbeelding - Credit, name: heroCredit, widget: markdown}
          - {label: Formulier - Titel, name: formTitle, widget: string}
          - {label: Formulier - Tekst, name: formText, widget: markdown}
  - name: "genres"
    label: "genres"
    editor:
      preview: false
    label_singular: "genre"
    folder: "genres"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}
  - name: "audiences"
    label: "publiek"
    editor:
      preview: false
    label_singular: "publiek"
    folder: "audiences"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Naam", name: "title", widget: "string"}