backend:
  name: git-gateway
  repo: pmcp/podiumaanhuis

# when using the default proxy server port
# To run local backend git: npx netlify-cms-proxy-server
local_backend: true

media_folder: "src/assets/uploads"
public_folder: "/uploads"

publish_mode: editorial_workflow


collections:
  - name: "pages"
    label: "Pages"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "homepages"
    label: "Homepage"
    files:
      - label: "Home"
        name: "home"
        file: "pages/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Hoofdafbeelding, name: heroImage, widget: image}
          - {label: Hoofdafbeelding - Credit, name: heroCredit, widget: markdown}